color spacegray
set background=dark
filetype plugin indent on
syntax enable

hi! link Pmenu StatusLine
hi! link PmenuSel WildMenu

set autochdir
set autoread
set autoindent smartindent
set belloff=all
set backspace=indent,eol,start
set formatoptions+=j
set hidden
set incsearch ignorecase smartcase noshowmatch
set number
set nowrap
set pastetoggle=<F2>
set splitright splitbelow
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab smarttab
set ttimeoutlen=100
set undofile undodir=~/.vim/tmp/undo
set viminfofile=$HOME/.vim/.viminfo
set wildignore=*.out,*.o,*.obj,.git,*.exe
set wildmenu

nnoremap <C-n> :bn<CR>
nnoremap <C-p> :bp<CR>
cnoremap Wq wq
cnoremap WQ wq
cnoremap Q q
cnoremap Qa qa
cnoremap W w
