set term=screen-256color
set t_Co=16
set background=dark
filetype plugin indent on
syntax enable

hi Comment      cterm=NONE    ctermfg=4
hi LineNr       cterm=NONE    ctermfg=8
hi PmenuSel     cterm=NONE    ctermfg=NONE  ctermbg=4
hi Pmenu        cterm=NONE    ctermfg=NONE  ctermbg=8
hi MatchParen   cterm=BOLD    ctermfg=6     ctermbg=NONE
hi StatusLineNC cterm=NONE    ctermfg=0     ctermbg=8
hi StatusLine   cterm=NONE    ctermfg=NONE  ctermbg=8
hi Visual       cterm=REVERSE ctermfg=NONE  ctermbg=NONE
hi WildMenu     cterm=NONE    ctermfg=NONE  ctermbg=4

set autochdir
set autoread
set autoindent
set belloff=all
set backspace=indent,eol,start
set formatoptions+=j
set hidden
set incsearch ignorecase smartcase noshowmatch
set number
set nowrap
set pastetoggle=<F2>
set splitright splitbelow
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab
set ttimeoutlen=100
set undofile undodir=~/.vim/tmp/undo
set viminfofile=$HOME/.vim/.viminfo
set wildignore=*.out,*.o,*.obj,*.swp,node_modules,.git,*.exe
set wildmenu

nnoremap <C-n> :bn<CR>
nnoremap <C-p> :bp<CR>
cnoremap Wq wq
cnoremap WQ wq
cnoremap Q q
cnoremap Qa qa
cnoremap W w
