set background=light
filetype plugin indent on
syntax enable

hi LineNr                   ctermfg=3
hi StatusLineNC cterm=NONE  ctermfg=232 ctermbg=8
hi StatusLine   cterm=NONE  ctermfg=232 ctermbg=7
hi Visual       cterm=NONE  ctermfg=232 ctermbg=8
hi WildMenu     cterm=BOLD  ctermfg=232 ctermbg=6
hi PmenuSel     cterm=BOLD  ctermfg=232 ctermbg=6
hi Pmenu        cterm=NONE  ctermfg=232 ctermbg=8
hi IncSearch    cterm=BOLD  ctermfg=232 ctermbg=6
hi MatchParen   cterm=BOLD  ctermfg=6   ctermbg=NONE
hi Statement                ctermfg=3 

set autochdir
set autoread
set autoindent smartindent
set belloff=all
set backspace=indent,eol,start
set formatoptions+=j
set hidden
set incsearch ignorecase smartcase noshowmatch
set number
set nowrap
set pastetoggle=<F2>
set splitright splitbelow
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab smarttab
set ttimeoutlen=100
set undofile undodir=~/.vim/tmp/undo
set viminfofile=$HOME/.vim/.viminfo
set wildignore=*.out,*.o,*.obj,*.swp,node_modules,.git,*.exe
set wildmenu

nnoremap <C-n> :bn<CR>
nnoremap <C-p> :bp<CR>
cnoremap Wq wq
cnoremap WQ wq
cnoremap Q q
cnoremap Qa qa
cnoremap W w
