HISTFILE="$HOME/.zsh/.zsh_history"
HISTSIZE=1000
SAVEHIST=1000

# Load all stock functions (from $fpath files) called below.
autoload -U compaudit
autoload -U compinit -d ~/.zsh/.zcompdump

# Load colors
autoload -U colors && colors

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Set default editor for git
export GIT_EDITOR=vim

# Set default editor for manpages
export MANPAGER="vim -M +MANPAGER - +set\ nonumber"

# enable true color support for neovim
# export nvim_tui_enable_true_color=1

export PATH="$PATH:$HOME/.local/bin"

# Enable vi mode
set -o vi

setopt multios
setopt prompt_subst
setopt appendhistory

# Case insensitive completion
compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'

alias ls="ls --color=auto"
alias lsa="ls -Ap"
alias lsd="ls -lAptr"
alias vi="vim"
alias py="python3.8"
alias diff="diff --color"

PROMPT="%F{208}[%B%n@%M] %F{4}%1d %F{208}λ %F{15}"
RPROMPT="%t"
