#!/usr/bin/env zsh
setopt appendhistory
setopt rm_star_wait
setopt multios
setopt prompt_subst
unsetopt BEEP

#export PATH="$PATH:$HOME/.local/bin"
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
export PATH="$HOME/dev/go/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export NOTES="$HOME/Desktop/notes/"
export EDITOR="vim"
export ZSH="$HOME/.oh-my-zsh"

set -o vi

HISTFILE="$HOME/.zsh/.zsh_history"
HISTSIZE=1000
SAVEHIST=1000
kernel=$(uname -s)

# Disable ctrl-s which pauses the terminal
stty stop ''

# Auto completion
autoload -U compinit -d ~/.zsh/.zcompdump
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
compinit

# Enable v to edit-and-execute
autoload -U edit-command-line 
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# Aliases
alias diff="diff --color"
alias vps="ssh quinn@173.255.215.170 -p 65535"

if [[ $kernel = "Darwin" ]]
then
    alias ls="ls -G"
else
    alias ls="ls --color=auto"
fi

if [[ $UID = 0 ]]
then
  username="%F{1}%n"
  symbol="#"
else
  username="%F{2}%n"
  symbol='%%'
fi

PROMPT="%B$username@%M:%F{4}%1~%F{15}$symbol%b "
#RPROMPT="%t"
