setopt appendhistory
setopt rm_star_wait
setopt multios
setopt prompt_subst
unsetopt BEEP

export PATH="$PATH:$HOME/.local/bin"
export NOTES="$HOME/Desktop/notes/"
export PASERVER=192.168.0.57
export EDITOR="vim"

set -o vi

HISTFILE="$HOME/.zsh/.zsh_history"
HISTSIZE=1000
SAVEHIST=1000

# Disable ctrl-s which pauses the terminal
stty stop ''

# Auto completion
autoload -U compinit -d ~/.zsh/.zcompdump
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
compinit

# Enable v to edit-and-execute
autoload -U edit-command-line 
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

alias ls="ls --color=auto"
alias py="python3"
alias diff="diff --color"

PROMPT="%B%F{2}%n@%M:%F{4}%1~%F{15}%% %F{15}%b"
RPROMPT="%t"
